title: Stateless Machine
description: Your blog description
baseurl: ""
url: "https://statless.computer"
author:
  name: vm
  email: vm@stateless.computer

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/1ikeadragon"
      
# If you want to link only specific pages in your header, add the path to the
# pages here, otherwise all pages will be linked
header_pages:
  - about.md
  show_excerpts: true
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/jekyll/1ikeadragon"
    - title: Xitter
      icon: x-twitter
      url: "https://x.com/cvewhen"
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/debxrshi"
