title: Stateless Machine
description: Your blog description
baseurl: ""
url: "https://statless.computer"
author:
  name: vm
  email: vm@stateless.computer



markdown: kramdown
highlighter: rouge
theme: minima


plugins:
  - jekyll-feed
  - jekyll-sitemap

minima:
  show_excerpts: true
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/jekyll/1ikeadragon"
    - title: Xitter
      icon: x-twitter
      url: "https://x.com/cvewhen"
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/debxrshi"
