title: Stateless Machine
description: scratch the itch
baseurl: ""
url: "https://stateless.computer"
author:
  name: vm
  email: vm@stateless.computer

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  skin: auto
  show_excerpts: true
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/1ikeadragon"
    - title: Xitter
      icon: x-twitter
      url: "https://x.com/cvewhen"
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/debxrshi"
